### ISSUE TITLE
About training vida source model 

### ISSUE THREAD

**Issue by daeunni** [Yangsenqiao/vida#7]
Hi, @Yangsenqiao, thanks for releasing your code. I really appreciate it. 
Btw, how can I train by myself [this source model](https://drive.google.com/file/d/13R0ZoHaUUXL4PYHWWIwl2NvEcU_3JJxU/view) using your code base? 

Thanks.

**Comment by Yangsenqiao** [comment]
Thank you for your interest in our work. I recommend that you follow these two repositories.
https://github.com/jeonsworld/ViT-pytorch
https://github.com/kentaroy47/vision-transformers-cifar10

**Comment by daeunni** [comment]
Thanks a lot Yangsenqiao! 

Btw, while reimplementing your code and running source_vit.sh with the CIFAR10 dataset, I got pretty different source-only results like below. 

```
[24/03/22 16:27:47] [cifar10c_vit.py:   68]: not resetting model
[24/03/22 16:29:41] [cifar10c_vit.py:   87]: error % [gaussian_noise5]: 88.48%
[24/03/22 16:29:41] [cifar10c_vit.py:   70]: not resetting model
[24/03/22 16:31:37] [cifar10c_vit.py:   87]: error % [shot_noise5]: 87.51%
[24/03/22 16:31:37] [cifar10c_vit.py:   70]: not resetting model
[24/03/22 16:33:33] [cifar10c_vit.py:   87]: error % [impulse_noise5]: 92.07%
[24/03/22 16:33:33] [cifar10c_vit.py:   70]: not resetting model
[24/03/22 16:35:29] [cifar10c_vit.py:   87]: error % [defocus_blur5]: 89.76%
[24/03/22 16:35:29] [cifar10c_vit.py:   70]: not resetting model
[24/03/22 16:37:26] [cifar10c_vit.py:   87]: error % [glass_blur5]: 89.25%
[24/03/22 16:37:26] [cifar10c_vit.py:   70]: not resetting model
[24/03/22 16:39:34] [cifar10c_vit.py:   87]: error % [motion_blur5]: 88.75%
[24/03/22 16:39:34] [cifar10c_vit.py:   70]: not resetting model
[24/03/22 16:41:32] [cifar10c_vit.py:   87]: error % [zoom_blur5]: 89.07%
[24/03/22 16:41:32] [cifar10c_vit.py:   70]: not resetting model
[24/03/22 16:43:29] [cifar10c_vit.py:   87]: error % [snow5]: 89.86%
[24/03/22 16:43:29] [cifar10c_vit.py:   70]: not resetting model
```

I just utilized these config you provided. 

```
MODEL:
  ADAPTATION: source
  ARCH: Standard_VITB
DATA_DIR: /dataset
TEST:
  BATCH_SIZE: 40
CORRUPTION:
  DATASET: cifar10
  SEVERITY:
    - 5
  TYPE:
    - gaussian_noise
    - shot_noise
    - impulse_noise
    - defocus_blur
    - glass_blur
    - motion_blur
    - zoom_blur
    - snow
    - frost
    - fog
    - brightness
    - contrast
    - elastic_transform
    - pixelate
    - jpeg_compression
```

I would be really appreciate if you have some ideas!
